package ru.dronix.entity;
// Generated 16.09.2016 19:06:41 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Crashed generated by hbm2java
 */
@Entity
@Table(name="crashed"
    ,catalog="db_shop"
)
public class Crashed  implements java.io.Serializable {


     private Integer crashedId;
     private Integer crashedIdProducts;
     private Integer crashedPrice;
     private Integer crashedCount;
     private Date crashedDatatime;
     private Integer crashedIp;

    public Crashed() {
    }

    public Crashed(Integer crashedIdProducts, Integer crashedPrice, Integer crashedCount, Date crashedDatatime, Integer crashedIp) {
       this.crashedIdProducts = crashedIdProducts;
       this.crashedPrice = crashedPrice;
       this.crashedCount = crashedCount;
       this.crashedDatatime = crashedDatatime;
       this.crashedIp = crashedIp;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="crashed_id", unique=true, nullable=false)
    public Integer getCrashedId() {
        return this.crashedId;
    }
    
    public void setCrashedId(Integer crashedId) {
        this.crashedId = crashedId;
    }

    
    @Column(name="crashed_id_products")
    public Integer getCrashedIdProducts() {
        return this.crashedIdProducts;
    }
    
    public void setCrashedIdProducts(Integer crashedIdProducts) {
        this.crashedIdProducts = crashedIdProducts;
    }

    
    @Column(name="crashed_price")
    public Integer getCrashedPrice() {
        return this.crashedPrice;
    }
    
    public void setCrashedPrice(Integer crashedPrice) {
        this.crashedPrice = crashedPrice;
    }

    
    @Column(name="crashed_count")
    public Integer getCrashedCount() {
        return this.crashedCount;
    }
    
    public void setCrashedCount(Integer crashedCount) {
        this.crashedCount = crashedCount;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="crashed_datatime", length=19)
    public Date getCrashedDatatime() {
        return this.crashedDatatime;
    }
    
    public void setCrashedDatatime(Date crashedDatatime) {
        this.crashedDatatime = crashedDatatime;
    }

    
    @Column(name="crashed_ip")
    public Integer getCrashedIp() {
        return this.crashedIp;
    }
    
    public void setCrashedIp(Integer crashedIp) {
        this.crashedIp = crashedIp;
    }




}


